### ISSUE TITLE
Move website documents to Github

### ISSUE THREAD

**Issue by schnuerle** [openmobilityfoundation/governance#2]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish this had a [...]

Hard to find OMF documents.

**Describe the solution you'd like**

Move PDFs from website to here in Github in a 'documents' folder.   Point website links here.  

**Describe alternatives you've considered**

Leave as is.

**Additional context**
Add any other context or screenshots about the feature request here. Links are helpful too.

Link to current location in Wordpress. https://www.openmobilityfoundation.org/resources/

**Comment by jfh01** [comment]
As discussed on last week's wg-ops, I like the idea, but would prefer to hold off on a migration project for now. It's a big lift and I want to wait until we have a compelling reason for it.

**Comment by johnclary** [comment]
Totally reasonable. For the future discussion, [Gitbook](https://www.gitbook.com/) might be a good compromise. It serves markdown in a pretty wiki format. So we could not fuss with the OMF website but link to Gitbook for the VC'd documents.

**Comment by johnclary** [comment]
Alternatively, we could iframe these docs in the Wordpress site, or possibly use some plugin that pulls in/renders the markdown files from Github seamlessly.

**Comment by schnuerle** [comment]
All documents from the website are now moved to the governance repo and links updated.  

If we want to discuss using Pages later (I think a more robust solution than Gitbook) we can open a new issue to discuss.
