### ISSUE TITLE
Criteria for inclusion in the governance repo

### ISSUE THREAD

**Issue by jfh01** [openmobilityfoundation/governance#4]
We currently have three requirements for items that live in the repo:

* Are 100% public facing.
* Are not managed directly by WG or Committee leaders
* Are relevant to more than one OMF repo/committee/group

Would suggest replacing the 2nd and 3rd bullet with

* Are not better suited for a WG or Committee-specific repo

Reasons being that some Committees (like Strategy) may want to publish into this repo rather than have their own, and there may be some topics (ex: guidance on using the Policy API) that are specific to a particular repo/WG, but which don't belong as part of the spec.

**Comment by schnuerle** [comment]
Looks good and is working for now.
