### ISSUE TITLE
Should governance/technical/GBFS_and_MDS.md explain differences between /vehicles and GBFS?

### ISSUE THREAD

**Issue by jfh01** [openmobilityfoundation/governance#6]
It may be useful for this document to be extended to explicitly map GBFS fields to `/vehicles`, and to provide guidance that suggests the use of `/vehicles` as an alternative to GBFS in regulatory contexts. Had initial discussion with @heidiguenin and @schnuerle. Will continue to discuss as we speak with the GBFS and MDS communities and learn more about what would be most valuable.

**Comment by schnuerle** [comment]
Have a draft document about this.  I can pull this together into a Wiki page with additional info from the GBFS webinar slides.

**Comment by schnuerle** [comment]
Have some [draft information here](https://docs.google.com/document/d/13hDgRn5wBPi5M5qN8H6-bbWiSkvvenGlViy0Q0h4sFI/edit).  Which part of this should be included into the MDS/GBFS doc?

**Comment by schnuerle** [comment]
I added the smaller chart to the page, and a link to the Google document for more details:

https://github.com/openmobilityfoundation/governance/blob/main/technical/GBFS_and_MDS.md#real-time-status-differences

Feedback appreciated.

**Comment by schnuerle** [comment]
Closing this issue. Looks like the page is good and being used.
